{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-wiki.serviceAccountName" . }}
  labels:
    {{- include "llm-wiki.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
