"""initial

Revision ID: ae59439c49c9
Revises: 
Create Date: 2026-06-07 20:07:54.751760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae59439c49c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('charter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cadence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_bindings', sa.JSON(), nullable=True),
    sa.Column('ingest_config', sa.JSON(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sub'), ['sub'], unique=True)

    op.create_table('usergroup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usergroup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usergroup_name'), ['name'], unique=False)

    op.create_table('chatmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_project_id'), ['project_id'], unique=False)

    op.create_table('chatsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sdk_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('viewer_sdk_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatsession_project_id'), ['project_id'], unique=True)

    op.create_table('confluenceoauthtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cloud_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confluenceoauthtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confluenceoauthtoken_project_id'), ['project_id'], unique=True)

    op.create_table('confluencespace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('space_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confluencespace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confluencespace_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confluencespace_slug'), ['slug'], unique=False)

    op.create_table('githuboauthtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('github_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('githuboauthtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_githuboauthtoken_project_id'), ['project_id'], unique=True)

    op.create_table('ingestrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('log', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestrun_project_id'), ['project_id'], unique=False)

    op.create_table('projectgrouprole',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'group_id')
    )
    op.create_table('projectmember',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('repo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repo_slug'), ['slug'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_greenfield', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_project_id'), ['project_id'], unique=False)

    op.create_table('usergroupmember',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('webexoauthtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webexoauthtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webexoauthtoken_project_id'), ['project_id'], unique=True)

    op.create_table('webexroom',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webex_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webexroom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webexroom_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webexroom_slug'), ['slug'], unique=False)

    op.create_table('pagerevision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagerevision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagerevision_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagerevision_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagerevision_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagerevision_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagerevision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagerevision_report_id'))
        batch_op.drop_index(batch_op.f('ix_pagerevision_project_id'))
        batch_op.drop_index(batch_op.f('ix_pagerevision_path'))
        batch_op.drop_index(batch_op.f('ix_pagerevision_created_at'))

    op.drop_table('pagerevision')
    with op.batch_alter_table('webexroom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webexroom_slug'))
        batch_op.drop_index(batch_op.f('ix_webexroom_project_id'))

    op.drop_table('webexroom')
    with op.batch_alter_table('webexoauthtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webexoauthtoken_project_id'))

    op.drop_table('webexoauthtoken')
    op.drop_table('usergroupmember')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_project_id'))

    op.drop_table('report')
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_slug'))
        batch_op.drop_index(batch_op.f('ix_repo_project_id'))

    op.drop_table('repo')
    op.drop_table('projectmember')
    op.drop_table('projectgrouprole')
    with op.batch_alter_table('ingestrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestrun_project_id'))

    op.drop_table('ingestrun')
    with op.batch_alter_table('githuboauthtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_githuboauthtoken_project_id'))

    op.drop_table('githuboauthtoken')
    with op.batch_alter_table('confluencespace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confluencespace_slug'))
        batch_op.drop_index(batch_op.f('ix_confluencespace_project_id'))

    op.drop_table('confluencespace')
    with op.batch_alter_table('confluenceoauthtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confluenceoauthtoken_project_id'))

    op.drop_table('confluenceoauthtoken')
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatsession_project_id'))

    op.drop_table('chatsession')
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessage_project_id'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_created_at'))

    op.drop_table('chatmessage')
    with op.batch_alter_table('usergroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usergroup_name'))

    op.drop_table('usergroup')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sub'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
